version: '3.8'

networks:
    dev:

services:
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog-container
        restart: always
        ports:
            - 8025:8025
            - 1025:1025
        networks:
            - dev
    web:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www:delegated
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - dev

    php:
        restart: unless-stopped
        container_name: php-container
        networks:
            - dev
        build:
            context: './.docker/php'
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - './:/var/www:delegated'
        depends_on:
            - db
            - mercure

    db:
        image: 'mariadb:latest'
        environment:
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: app
        networks:
            - dev
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - '3307:3306'

    mercure:
        image: dunglas/mercure
        container_name: mercure-container
        restart: unless-stopped
        ports:
            - '3000:80'
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
            DEBUG: 1
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://127.0.0.1:8000 http://localhost:8000
                ui: true
                subscriptions: true
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config
        networks:
            - dev

    redis:
        restart: unless-stopped
        image: redis:latest
        container_name: redis
        hostname: redis
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        networks:
            - dev

volumes:
  db_data:
  mercure_data:
  mercure_config:
  redis-data:
    driver: local
